# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4269a7cca49d9bbe36d558aeacc96a5f6636dc359819a4777924f3d84086ed612a298a2d26998e72a0f900bf6ed4fc4b5172b455bda9ed3c14a5441ac6d0a9fc

test:
  secret_key_base: 0064b702be64e03b612fe6ebc499b13bc83053660ad14dfef18f05466ab40e8bb3e028dfa2e343d3dc7bd10adb1611e985415665449e687d1d50572e1b9b774b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
